# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='updated_by',
        ),
    ]
