# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180128_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='is_active',
        ),
    ]
