# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180128_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentary',
            field=models.TextField(max_length=500, verbose_name='Comentario'),
        ),
    ]
