# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 04:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180128_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z-ñÑ-áéíóúÁÉÍÓÚ ]+$', code='Inválido', message='Este campo sólo permite letras.')], verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
